# Generated by Django 3.1.6 on 2021-02-11 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('categoria', models.CharField(choices=[('Defi', 'Defi'), ('Trading', 'Trading'), ('Noticias', 'Noticias'), ('Educacion', 'Educacion')], default='Noticias', max_length=20)),
                ('thumbnail', models.CharField(default='https://coinsmos.s3.us-east-2.amazonaws.com/coinastrologo.png', max_length=10000)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'Borrador'), (1, 'Publicacion')], default=0)),
                ('destacado', models.IntegerField(choices=[(0, 'Estandar'), (1, 'Destacado')], default=0)),
                ('banner', models.CharField(default='https://i.ibb.co/5FqNvJP/banner3.png', max_length=10000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
