# Generated by Django 3.1.7 on 2021-03-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=200)),
                ('marketcap', models.CharField(max_length=200)),
                ('volumen', models.CharField(max_length=200)),
                ('supply', models.CharField(max_length=200)),
                ('change', models.CharField(max_length=200)),
                ('imagen', models.CharField(default='https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1547033579', max_length=600)),
            ],
        ),
    ]
