# Generated by Django 3.1.7 on 2021-03-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_section', '0004_auto_20210308_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='marketcap',
            field=models.BigIntegerField(),
        ),
    ]
